version: '3.9'

services:
  
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=rentalx
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
    volumes:
      - pgdata:/data/postgres
  
  rentalx:
    build: .
    container_name: rentalx
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
